# Generated by ariadne-codegen
# Source: ./gql/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class AllPosts(BaseModel):
    list_posts: "AllPostsListPosts" = Field(alias="listPosts")


class AllPostsListPosts(BaseModel):
    success: bool
    errors: Optional[List[Optional[str]]]
    post: Optional[List[Optional["AllPostsListPostsPost"]]]


class AllPostsListPostsPost(BaseModel):
    id: str
    title: str
    description: str
    created_at: str


AllPosts.model_rebuild()
AllPostsListPosts.model_rebuild()
AllPostsListPostsPost.model_rebuild()
