# Generated by ariadne-codegen
# Source: ./gql/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class CreateNewPost(BaseModel):
    create_post: "CreateNewPostCreatePost" = Field(alias="createPost")


class CreateNewPostCreatePost(BaseModel):
    post: Optional["CreateNewPostCreatePostPost"]
    success: bool
    errors: Optional[List[Optional[str]]]


class CreateNewPostCreatePostPost(BaseModel):
    id: str
    title: str
    description: str
    created_at: str


CreateNewPost.model_rebuild()
CreateNewPostCreatePost.model_rebuild()
CreateNewPostCreatePostPost.model_rebuild()
