# Generated by ariadne-codegen
# Source: ./gql/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetPost(BaseModel):
    get_post: "GetPostGetPost" = Field(alias="getPost")


class GetPostGetPost(BaseModel):
    post: Optional["GetPostGetPostPost"]
    success: bool
    errors: Optional[List[Optional[str]]]


class GetPostGetPostPost(BaseModel):
    id: str
    title: str
    description: str


GetPost.model_rebuild()
GetPostGetPost.model_rebuild()
GetPostGetPostPost.model_rebuild()
